"""initial

Revision ID: 7f1aef896dc8
Revises: 
Create Date: 2026-03-29 11:59:29.834557+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1aef896dc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=50), nullable=False, comment="User's first name"),
    sa.Column('last_name', sa.String(length=50), nullable=True, comment="User's last name"),
    sa.Column('date_of_birth', sa.Date(), nullable=False, comment="User's date of birth"),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False, comment="User's gender type"),
    sa.Column('email', sa.String(length=50), nullable=False, comment='Email'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment="User's activity status"),
    sa.Column('join_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Registration date and time'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
