"""initial

Revision ID: 41b71bc16f35
Revises: 
Create Date: 2024-01-27 20:39:02.402833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b71bc16f35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('packs',
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_status', sa.Enum('default', 'created_by_user', name='packcreatedstatuschoises'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_packs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packs'))
    )
    op.create_table('cards',
    sa.Column('front_side', sa.String(length=64), nullable=False),
    sa.Column('back_side', sa.String(length=64), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], name=op.f('fk_cards_pack_id_packs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('packs')
    op.drop_table('users')
    # ### end Alembic commands ###
